.Dd nfy\-VERSRION
.Dt NFY 1
.Os
.Sh NAME
.Nm nfy
.Nd a minimal notification program for X
.Sh SYNOPSIS
.Nm
.Ar str...
.Sh DESCRIPTION
.Nm
creates a temporary notification popup window and displays
all the arguments that were passed to it.
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@christosmarg.xyz
